### ISSUE TITLE
Dependency on batman / numpy makes it impossible to install TLS

### ISSUE THREAD

**Issue by dcf21** [hippke/tls#103]
**Describe the bug**

Has anybody else been finding it totally impossible to install TLS for about the past three months since numpy 1.22 was released?

**To Reproduce**

On a vanilla Ubuntu 22.04 machine (or 20.04 behaves the same):

dcf21@europa:/tmp/foo$ virtualenv venv
dcf21@europa:/tmp/foo$ ./venv/bin/pip install transitleastsquares
dcf21@europa:/tmp/foo$ ./venv/bin/python3
Python 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import transitleastsquares
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/foo/venv/lib/python3.10/site-packages/transitleastsquares/__init__.py", line 13, in <module>
    from transitleastsquares.main import transitleastsquares
  File "/tmp/foo/venv/lib/python3.10/site-packages/transitleastsquares/main.py", line 40, in <module>
    from transitleastsquares.transit import reference_transit, fractional_transit, get_cache
  File "/tmp/foo/venv/lib/python3.10/site-packages/transitleastsquares/transit.py", line 2, in <module>
    import batman  # https://www.cfa.harvard.edu/~lkreidberg/batman/
  File "/tmp/foo/venv/lib/python3.10/site-packages/batman/__init__.py", line 6, in <module>
    from .transitmodel import *
  File "/tmp/foo/venv/lib/python3.10/site-packages/batman/transitmodel.py", line 18, in <module>
    from . import _nonlinear_ld
ImportError: numpy.core.multiarray failed to import
>>>

The above example installs TLS using the PyPi repository, but I get exactly the same bahaviour if I download the code from GitHub and install via that route.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Python version 3.10
 - TLS Version [1.0.13]

**Additional context**

It would be really good to get this fixed quite urgently, since I'm trying to evaluate TLS as a possible transit-detection algorithm of choice for the PLATO pipeline, but obviously if it doesn't actually run then that's a bit of a disadvantage... :-)

**Comment by hippke** [comment]
Yes this is a [known problem with batman](https://github.com/lkreidberg/batman/issues/51).
There are two work-arounds:

1. If you can accept an older numpy, then `pip install numpy==1.21.1` (may need conda to force this exact version)
2. Download the batman package from Github, change  `numpy` to `oldest-supported-numpy` in batman's `pyproject.toml` file  and then doing a `pip install .`

If this doesn't get resolved soon (@lkreidberg please help, this is such a cool package), I will have to replace the usage of batman in TLS with e.g. PyTransit. Quite unfortunate situation.

**Comment by dcf21** [comment]
Thanks so much for the quick reply, @hippke . That's done the trick!

I had already tried doing (1), but I would never have guessed I had to do (2) as well.

I have a lot of sympathy for the unfortunate situation you're in - it seems to me the Python community should be worrying much more about how hard it is to reproduce a known-good Python environment from three months ago!

**Comment by hippke** [comment]
Fixed by batman 2.4.9. Please try `pip install batman-package --upgrade`.
I will leave this issue open for a few week to check if it solves the problem for everybody.
In case any issues remain, I have prepared a TLS version that uses PyTransit instead of batman-package. I could then change it out.
