### ISSUE TITLE
Installation issue conda

### ISSUE THREAD

**Issue by xiaomabo** [hippke/tls#37]
When I was trying to pip install, it reports 

(python37) [boma@16:48:11@~/transit/tls] pip install tls
Collecting tls
  Could not find a version that satisfies the requirement tls (from versions: )
No matching distribution found for tls

I have python 3.7 installed using Conda. Not sure which version is required by TLS.

**Comment by hippke** [comment]
Please use `pip install transitleastsquares`. You tried the package `tls` which is not `transitleastsquares`.

**Comment by hippke** [comment]
I'm sorry the package name was incorrect in the readme. I fixed it.
