### ISSUE TITLE
Ensure matplotlib is added as a dependancy during package installation

### ISSUE THREAD

**Issue by T0T4R4** [hippke/tls#69]
I tried to run your examples and some uses matplotlib. It would be nice to have it added to the overall dependancies when tls gets installed.

**Comment by hippke** [comment]
Hi! You can run TLS without matplotlib. It doesn't have a dependency. Only if you want to visualize the result, as in the tutorial, it is convenient to use matplotlib. You can install it using ``conda install matplotlib`` or ``pip install matplotlib``. Alternatively, you can use other plotting tools.
