### ISSUE TITLE
Uncertanties in the ephemerides, transit duration etc.?

### ISSUE THREAD

**Issue by MilevaE** [hippke/tls#74]
Hi, 
using TLS I found an hiden signal which: 

```
Period 1.32471 d at T0= 1545.5887359991175
Period 1.32471 d at T0 (JD) = 2458545.588735999
18 transit times in time series: ['1545.58874', '1546.91345', '1548.23816', '1549.56288', '1550.88759', '1552.21231', '1553.53702', '1554.86174', '1556.18645', '1557.51117', '1558.83588', '1560.16059', '1561.48531', '1562.81002', '1564.13474', '1565.45945', '1566.78417', '1568.10888']
Number of data points during each unique transit [ 9.  9.  9. 10. 10.  9.  9.  9.  0.  0.  9.  9.  0. 10.  9.  9.  9.  9.]
The number of transits with intransit data points 15
The number of transits with no intransit data points 3
Transit depth 0.99711 (at the transit bottom)
Transit duration (min) 18.79655
Transit depths (mean) [0.99509769 0.99837714 1.00028289 0.99666704 0.99655364 0.99587185
 0.99418039 0.99763466        nan        nan 1.00194123 0.9938278
        nan 0.99543035 1.00183443 0.99760156 0.99933798 0.99653153]
Transit depth uncertainties [0.00223717 0.002463   0.00280888 0.00213923 0.00265328 0.0025611
 0.00262064 0.00359985        nan        nan 0.00487221 0.00243405
        nan 0.0030145  0.00330284 0.0018631  0.0010523  0.00189251]
SNR 19.49318758226711
FAP 8.0032e-05
SDE 28.284621876567176
```
Which looks promising at first, isn't?. But there are few things I don't know how to manage. 
For example, If I want to plan observations of this potential candidate,  **How can I know the uncertainties of the ephemeris?  It could be possible  to have errors in the transit duration somehow?** It seems that I never obtain the same than the ones provides by TESS for known planet candidates ..

Thanks a lot!

**Comment by hippke** [comment]
Hi Mileva,
You can get an estimate for the period uncertainty from ``results.period_uncertainty``.
However, before you get too excited, you should thorougly vet your signal. Often, transit-like signals are caused by systematics (stellar, instrumental etc.). As an example of useful metrics, see Figure 1 in [this paper](https://arxiv.org/pdf/1905.09038.pdf). Can you make and share similar plots? I'm happy to assist further.

**Comment by MilevaE** [comment]
Hi Hippke!, 
thanks a lot for the link to the paper. I read it and I tried to follow it to improve my findings. I noticed an error in one of my steps, and now the results look less promising: 

```
Period 1.32471 d at T0= 1545.5887359991175
Period 1.32471 d at T0 (JD) = 2458545.588735999
Period Error 0.00100 d
Period Error 1.43514 min
18 transit times in time series: ['1545.58874', '1546.91345', '1548.23816', '1549.56288', '1550.88759', '1552.21231', '1553.53702', '1554.86174', '1556.18645', '1557.51117', '1558.83588', '1560.16059', '1561.48531', '1562.81002', '1564.13474', '1565.45945', '1566.78417', '1568.10888']
Number of data points during each unique transit [ 9.  9.  9. 10. 10.  9.  9.  9.  0.  0.  9.  9.  0. 10.  9.  9.  9.  9.]
The number of transits with intransit data points 15
The number of transits with no intransit data points 3
Transit depth 0.99711 (at the transit bottom)
Transit duration (min) 18.79655
Transit depths (mean) [0.99509769 0.99837714 1.00028289 0.99666704 0.99655364 0.99587185
 0.99418039 0.99763466        nan        nan 1.00194123 0.9938278
        nan 0.99543035 1.00183443 0.99760156 0.99933798 0.99653153]
Transit depth uncertainties [0.00223717 0.002463   0.00280888 0.00213923 0.00265328 0.0025611
 0.00262064 0.00359985        nan        nan 0.00487221 0.00243405
        nan 0.0030145  0.00330284 0.0018631  0.0010523  0.00189251]
SNR 3.517800689468416
FAP 8.0032e-05
SDE 10.80704973776568
```
As you can see, the SNR is too low.. :(
By the way, which do you think should be the minimum SNR to consider a signal as a potential candidate? 
Let me show you in any case the rest of results I obtained, I would like to know your opinion if possible: 

The detrended lightcurve (using WOTAN), after the removal of the two existing planets reported by TESS (by the way, I found them with better SNR and obtain the same result in period, transit duration etc. So, fantastic work done by TLS): 

![detrended](https://user-images.githubusercontent.com/29211450/61468636-036d9f00-a97e-11e9-8e8e-ee16bf26e2fa.png)


The periodogram: 

![SDE](https://user-images.githubusercontent.com/29211450/61468795-62331880-a97e-11e9-99aa-224bf7bf4365.png)
 

The entire set of transits of this potential candidate:

![full_transits](https://user-images.githubusercontent.com/29211450/61468857-82fb6e00-a97e-11e9-9759-d241036d79c2.png)

The phase folded: 

![phase_folded](https://user-images.githubusercontent.com/29211450/61468882-8db60300-a97e-11e9-8b61-293c529ce6ff.png)

The transit depths: 

![Transit_depths](https://user-images.githubusercontent.com/29211450/61468914-9d354c00-a97e-11e9-95c8-7f07c5bf97d1.png)

**Comment by hippke** [comment]
Hi Mileva,

Congratulations! You have most likely not found a new planet, but you have a working pipeline to find new planets! That's very good. 

The most commonly used SNR threshold in the literature is ~7, as it gives (assuming white noise) less than one false positive over the Kepler mission. Usually, SNR>10 looks visually convincing to people, which is not unimportant if you plan to publish your results. SNR~3 is, as you suspect, too low to be considered any further.

Don't let that discourage you. Keep searching!
Michael

**Comment by MilevaE** [comment]
Hi Hippke! 
yes, sure, I will keep searching :) 
thanks for your assistance!
