### ISSUE TITLE
Please provide a [Rs]

### ISSUE THREAD

**Issue by 3fon3fonov** [hippke/tls#75]
Hello Michael!

Can you please provide also as an output a_rs (semi-major axis in units of stellar radii), as this is an input parameter in "batman", and is easy later to take TLS results and feed batman again.

I see you have "rp_rs", which is great, but the semi-major axis is missing.

**Comment by hippke** [comment]
That‘s unfortunately not possible. It requires fitting a full model, e.g. using the PyTransit, juliet, or exoplanet package. You can calculate a rough estimate using Kepler‘s law with some assumptions on the masses of the bodies.

**Comment by 3fon3fonov** [comment]
I am sorry, I am not sure I understand. First, I can fit a full model myself using my “Exo-Striker” tool (which you should probably advertise more as it also uses the TLS). Juliet, The Exo-Striker, and correct me if i am wrong TLS, use the batman-package, which uses rp_rs as a parameter. So why not? How do you “feed” TLS? 

What usually i do with the Exo-Striker is to run TLS and when TLS is done adopt its parameters in order to star a full model, which so far relies on batman.

**Comment by hippke** [comment]
Yes, `TLS` uses `batman` to generate models. If you have a prior on any model parameter (perhaps from stability arguments, known planets, etc.), you can actual feed it into TLS and use that. There are also the model pre-sets `default`, `grazing` and `box`. 
If no model parameters are given, TLS uses the `default` model. This has been optimized with the average transit shape of small planets (Figure 2 in the [paper](https://arxiv.org/pdf/1901.02015.pdf)). In this model, `a_rs=23.1` (see [source](https://github.com/hippke/tls/blob/master/transitleastsquares/tls_constants.py)).
As this parameter is a fixed value, one should run a full model fit afterwards to find a "better" a_rs. After all, you want all parameters to be fitted, including limb darkening etc.
And thanks for the pointer to `Exo-Striker` - very cool package! I will advertise that in the future.

**Comment by 3fon3fonov** [comment]
Ok that explains a lot. I just thought that you are also varying these parameters too. Sorry if i missed this in the paper. About the Exo-Striker, i showed you a demo about 6 months ago, you must had forgotten.  

Trifon
