### ISSUE TITLE
Bug -- can not allocate memory

### ISSUE THREAD

**Issue by MilevaE** [hippke/tls#77]
Maybe not a bug, but an error in my code. 

**Describe the bug**
Suddenly, I started to have the following error: 

> OSError Traceback (most recent call last)
> <ipython-input-16-c0e86c613f90> in <module> 
>       2 ab, mass, mass_min, mass_max, radius, radius_min, radius_max = catalog_info(TIC_ID=TIC_ID)
>       3 model = transitleastsquares(time, global_final[i])
> ----> 4 results = model.power(u=ab,M_star=mass,R_star=radius, show_progress_bar=False)

> OSError: [Errno 12] Cannot allocate memory

The error itself is larger, but this is the final message

**To Reproduce**
I would like to explore a range of different `window_length` in order to explore the best detrending model to my set of data. This example is part of my code, which aims to reproduce a TESS detection. 

[tess2019226182529-s0015-0000000043064903-0151-s_lc.fits.zip](https://github.com/hippke/tls/files/3778592/tess2019226182529-s0015-0000000043064903-0151-s_lc.fits.zip)

```
## Already on my local folder:
url = 'tess2019226182529-s0015-0000000043064903-0151-s_lc.fits'
hdu = fits.open(url)
time = hdu[1].data['TIME']
flux = hdu[1].data['PDCSAP_FLUX']  # values with non-zero quality are nan or zero'ed
flux_err = hdu[1].data['PDCSAP_FLUX_ERR']  # values with non-zero quality are nan or zero'ed
time, flux, flux_err = cleaned_array(time, flux, flux_err)  # remove invalid values such as nan, inf, non, negative
flux_err = flux_err / numpy.median(flux)
flux = flux / numpy.median(flux)
TIC_ID = hdu[0].header['TICID']
ab, mass, mass_min, mass_max, radius, radius_min, radius_max = catalog_info(TIC_ID=TIC_ID)

## now I define the range of values to explore
from wotan import flatten
import numpy as np

wl=np.arange(1,5,1)
global_flatten_lc=np.zeros((len(wl),len(flux)))
global_trend_lc=np.zeros((len(wl),len(flux)))
for i in range(0,len(wl)):
    flatten_lc, trend_lc  = flatten(time, flux, window_length=wl[i], return_trend=True, method='biweight',break_tolerance=0.5)
    global_flatten_lc[i]=flatten_lc
    global_trend_lc[i]=trend_lc

## I clip some data 

global_final=np.zeros((len(wl),len(flux)))
for i in range(len(wl)):
    flatten = sigma_clip(global_flatten_lc[i], sigma_upper=3, sigma_lower=float('inf'))
    global_final[i]=flatten  

## I run the TLS for all the scenarios I set

TOTAL=np.zeros((len(wl),1))
SNR=np.zeros((len(wl),1))
SDE=np.zeros((len(wl),1))
for i in range(len(wl)):
    print(i)
    model = transitleastsquares(time, global_final[i])
    results = model.power(u=ab,M_star=mass,R_star=radius, show_progress_bar=False)
    TOTAL[i] = results.snr+results.SDE
    SNR[i] = results.snr
    SDE[i] = results.SDE 

```
To decide which is the best model, I define `TOTAL ` , but I'm not sure if this is the best (suggestions are welcome :) )

**Desktop (please complete the following information):**
 - OS: Linux, UBUNTU 16.04
 - Python version 3.7
 - TLS Version [1.0.23]

**Additional context**
I attach the lightcurve file from TESS. My intention is the send this code to a cluster, so I disabled the` progress bar` 

Thanks in advance!

**Comment by hippke** [comment]
I ran your script on Ubuntu 18.04, Python 3.7, TLS 1.0.23 and it ran fine. No error. Can you try on a different machine? I have seen out of memory errors before when processing hundreds of light curves. There is a memory leak in TLS which slowly fills up RAM. Sorry for that. Until I find and fix it, I recommend to batch-process perhaps 10 (or 50) light curves, and then take on the next batch. Use a bash script for that.

For the SNR and SDE, I recommend not to add them. They're different things and you shouldn't add apples and oranges. Choose one of them. Either is fine.

I would also recommend not to add SNR values from different searches. Depending on your detrending, you might get a detection for some values and other values smear it away. It's still a valid detection if it happens in any one of your runs. If something is detected above your threshold, you should generate a vetting sheet and examine it manually (or using a suitable machine learning vetting pipeline).
