### ISSUE TITLE
TLS crash

### ISSUE THREAD

**Issue by MXK606** [hippke/tls#79]
I'm trying to run TLS on my MacBook Pro 2019 in a Jupyter notebook and every time I run the code, it crashes with the following error in terminal;

`0%|          | 0/1874 periods | 00:00<?Transit Least Squares TLS 1.0.24 (21 November 2019)
Creating model cache for 27 durations
Searching 12878 data points, 1874 periods from 0.601 to 10.754 days
Using all 8 CPU threads
libc++abi.dylib: libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Couldn't close file`

I then tried to run it in Spyder instead but it crashes with the same error almost always. The exact same code runs fine in terminal with no errors. This started occurring around a week or two ago and was working completely fine before that. I had done no updates to any of the software at all so It can't be due to those but even after updating my macOS, Jupyter, Spyder, Python, it crashes prompting the error above. I found a similar issue on https://github.com/matplotlib/matplotlib/issues/15410 page but I can't seem to pin point the error source. I ran TLS with all default parameters. Hope you can help me out.

 - macOS Catalina 10.15.3
 - Python version 3.7
 - TLS Version 1.0.24

**Comment by hippke** [comment]
Hi, sorry for your trouble! Hope we'll get it sorted out. Can you post a short-as-possible piece of code which produces the crash? I'll try running it on various platforms I have at hand.

**Comment by MXK606** [comment]
The code is as simple as it can be similar to your first tutorial notebook;

`from transitleastsquares import transitleastsquares`
`model = transitleastsquares(time, flux) #time and flux here are basic arrays`
`results = model.power()`

I have even tried re-installing Anaconda and TLS on my device and it still prompts the same error. 
I guess it's mostly a crash between multiprocessing within TLS and macOS Catalina.

Thank you for helping me out!

**Comment by hippke** [comment]
Mhm, can you provide a complete example which causes the crash? I suspect some conflict perhaps with matplotlib.

**Comment by MXK606** [comment]
Hi, sorry for replying late but TLS now seems to work just fine.

**Comment by rachelbf** [comment]
Hi Michael, 
FYI: I had this same issue while running Python 3.7. I fixed it by upgrading matplotlib to 3.3.1.
