### ISSUE TITLE
Question: what does negative SDE mean?

### ISSUE THREAD

**Issue by jpdeleon** [hippke/tls#82]
TLS yields SDE array as a function of period. In some cases, I got negative SDEs. What does it mean? From your TLS paper:

"An SDE value of x for any given P means that the statistical significance of this period is xσ compared to the mean significance of all other periods."

A negative SDE doesn't mean the period is negative xσ significant, does it?

**Comment by hippke** [comment]
In pure noise, half the SDE values should be above zero, half below. It's normalized that way. Negative SDE values correspond to signals that are transit-shaped _peaks_ in the lightcurve, phased at that period. There is actually a physical use case for keeping it this way: You can use it to search for self-lensing (see Figure 2 in [this paper](https://arxiv.org/abs/1404.4379)).

**Comment by jpdeleon** [comment]
I see. That's cool! Since I am currently interested to look for transits only, I will clip SDE>0 for the meantime. Thank you!
