### ISSUE TITLE
Enhance APIs to provide time series models for visualization purposes

### ISSUE THREAD

**Issue by sriramsrao** [hippke/tls#85]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A call to `transitleastsquares.power()` returns the period information along with models for visualization purposes.  It would be nice if the APIs could be enhanced to return the models for visualization purposes.  For instance, the following APIs

- `fold(T0, period, duration)`
- `model(T0, period, duration)`

could return the time series corresponding to the phase folded model and the model that TLS computes.

**Describe alternatives you've considered**

**Additional context**

**Comment by hippke** [comment]
The model in normal time and in folded form is already available, see the [documentation](https://transitleastsquares.readthedocs.io/en/latest/Python%20interface.html#return-values).
The keywords are 
- `transitleastsquares.model_lightcurve_time`
- `transitleastsquares.model_lightcurve_model`
- `transitleastsquares.folded_phase`
- `transitleastsquares.folded_y`
- `transitleastsquares.model_folded_phase`
- `transitleastsquares.model_folded_model`

**Comment by sriramsrao** [comment]
The above solution requires me to build the model by calling power().  The APIs I am asking for are to reuse computed values for T0, period, and duration and generate the visualization curves.

**Comment by hippke** [comment]
First you must build (=calculate) the model. Afterwards, it becomes available and you can use it.

**Comment by sriramsrao** [comment]
Agreed.  In my use case, I build the model once and have all the params.  I just want the visualization curves later (perhaps in a different program) and I don't want to rebuild the model each time.

**Comment by sriramsrao** [comment]
I am bit puzzled why this is closed.  If you look at the lightkurve APIs, they have APIs such as fold(), where you pass in T0, duration, etc.  Are you closing the issue because this is an API/use case that you don't intend to support?  Given that this is an open source project, would be good if you comment on this aspect.t

**Comment by hippke** [comment]
I was under the impression that my explanation had solved your issue.
I have used both TLS and lightkurve extensively and don't understand your issue. Please explain. Can you provide some sample code which doesn't work? Or sketch a use-case step by step?

**Comment by sriramsrao** [comment]
Our use case is the following:

1. Run TLS to compute period/T0 information.  (Program 1).
2. Use an ML model to classify curves and generate probabilities of possible planet candidates (PCs).  (Program 2).
3.  Take the top few PC's and then visualize the curves. (Program 3).

With Program 3, I have to recompute the model with TLS to get the visualization information.  The model calculation is expensive (and is redundant), since I already have T0/period/epoch from Program 1.  The ask here is that, if I can APIs that take the previously computed T0/period/epoch and just get me back the visualization without having to recompute the whole model, that'd speed up the visualization step (Program 3) considerably.

Hope this clarifies.  Thanks.

**Comment by hippke** [comment]
You can do this without any changes to the code. Why would you re-compute the TLS model? The model is just a numpy array which you can store, save, etc. as you wish.

**Comment by sriramsrao** [comment]
Had tried that. Was running into disk space issues (even though I had compressed the data) :).

**Comment by hippke** [comment]
The model arrays will be the same size as your input data. That can only be a few MB.
