### ISSUE TITLE
Bug: Default Limb Darkening Coefficients overriding input

### ISSUE THREAD

**Issue by kboley3** [hippke/tls#91]
**Describe the bug**
The default limb darkening coefficients are being used when specifying limb darkening coefficients

**To Reproduce**
Using TESS FFI and 2 min data
This is what is input:

Typ='quadratic'
limb=[0.22248164, 0.3035742 ]
model = transitleastsquares(time, Flux)
results = model.power(transit_template=template,show_progress_bar=False,limb_dark=Typ, u=limb )

3. Which step or function in TLS fails? The issue is in the power function.  It doesn't fail, it just overrides the input

**Desktop (please complete the following information):**
 - OS: MacOS
 - Python version: 3.6
 - TLS Version [1.0.25 and 1.0.26]

**Comment by hippke** [comment]
Please check the syntax. It should be:
`results = model.power(limb_dark='quadratic', u=[0.22248164, 0.3035742 ])`

**Comment by hippke** [comment]
Can you post a full working example?

**Comment by kboley3** [comment]
It was just a syntax error.  Thank you! I apologize for the inconvenience
