### ISSUE TITLE
Relax minimum period

### ISSUE THREAD

**Issue by gmorello** [hippke/tls#94]
When analysing TESS data, it looks like the minimum period for the transit search (power) cannot go below 0.602 day, even if I try to force a smaller period_min. As there are some TOIs with shorter periods, it would be useful to either remove this limit in case the user requires a smaller limit (even if unphysical) or to use a looser constrain (around 0.1 day to be on the very safe side). Perhaps adding a warning if this might cause some statistical or physical issues?

**Comment by hippke** [comment]
Hi @gmorello this would be an easy change to make in the code. But...what's the purpose? Is there a chance to find objects with such short periods? What would they be like?

**Comment by gmorello** [comment]
Hi @hippke thanks for your comment. If you look at the list of TOIs here (https://exofop.ipac.caltech.edu/tess/view_toi.php) and order them by period, there should be 116 of them with orbital period shorter than 0.6, the minimum being 0.15 days.
Probably none of them have been confirmed yet, but I expect that a few of them will be validated. Those around small stars should have a chance to exist.

**Comment by hippke** [comment]
OK, I have released TLS 1.0.28 which you can install/update via pip. [This example](https://github.com/hippke/tls/releases/tag/1.0.28) should give you a grid starting at 0.1 days. Let me know if it works!

**Comment by gmorello** [comment]
I can confirm that it works, but not for arbitrary masses and radius limits. It is fine for me anyway, thank you.
