### ISSUE TITLE
Add `verbose` kwarg to transitleastsquares

### ISSUE THREAD

**Issue by lgbouma** [hippke/tls#96]
When running TLS on large sets of light curves, four lines are by default printed to stdout, _e.g._,
```
Transit Least Squares TLS 1.0.28 (13 June 2021)
Creating model cache for 43 durations
Searching 634 data points, 4418 periods from 0.601 to 26.25 days
Using 1 of 64 CPU threads
```

I'd like to have the option to not print these lines if I don't want to, mostly to prevent polluting log output.

One way this could be implemented would be adding a `verbose` kwarg, so that one could call `model = transitleastsquares(time,flux, verbose=False)` if they didn't want the output.  `verbose` would by default be set to True, so that the default functionality would not change.

This would also be propagated to `transitleastsquares.transit.get_cache`.

I could submit a PR for this, if it were of interest.  Otherwise, happy to just keep it on my fork!

Many thanks --
Luke

**Comment by lgbouma** [comment]
See e.g., https://github.com/lgbouma/tls/commit/117c956bacd03ebd6538ff501f01a5ce6cf62dc1

**Comment by hippke** [comment]
Hey, that's a great idea. Happy to accept the PR right away. Thank you!

**Comment by hippke** [comment]
I released a new version on PyPI and github, but noticed that it's not working.
Should there be also a change in `validate.py`?

**Comment by lgbouma** [comment]
Hi Michael, I don't think anything is printed in `validate.py`... do you mean to add a validation assertion to ensure that the "verbose" input is indeed boolean?

My MWE here is:
```
import numpy as np; import transitleastsquares as tls
time, flux = np.linspace(1,2,100), np.linspace(0.99,1.01,100)
model = tls.transitleastsquares(time,flux,verbose=False)
result = model.power(show_progress_bar=False)
```

which does not print anything to stdout (except for a warning because I didn't set R_star and M_star).

**Comment by hippke** [comment]
Something seems wrong with my conda. I have to try on a different machine on the weekend. Will report back.

**Comment by hippke** [comment]
OK, I fixed various issues and put a new version .30 on PyPI.
The ``verbose`` is now included in the ``power`` method, as for the other parameters. It's also included in the documentation.

Thanks again for this PR!
